name: CI / Build & Deploy

on:
  push:
    branches:
      - main # ← lista en YAML, no corchetes (opcional pero más legible)

jobs:
  deploy: # mejor nombre que “build”, porque no compila nada
    runs-on: ubuntu-latest
    environment: ci-deploy

    steps:
      # 0) (Opcional) registrar el commit en el log del workflow
      - name: Checkout code
        uses: actions/checkout@v4

      # 1) Conexión SSH y despliegue
      - name: Ship code & deploy on VPS
        uses: appleboy/ssh-action@v1.0.0 # owner/repo@version: ✔️
        with:
          host: ${{ secrets.VPS_IP }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }} # llave privada **sin passphrase**
          # puerto 22 por defecto; si usas otro añade `port: 2222`
          script: |
            set -e                       # aborta si algo falla

            echo "::group::Pull repo"
            cd /srv/gridbot

            # ⚠️ Esto descarta cualquier cambio local
            git reset --hard HEAD
            git clean -fd

            git pull origin main
            echo "::endgroup::"

            echo "::group::Compose build & up"
            docker compose up -d --build --force-recreate --remove-orphans
            echo "::endgroup::"
